### PR TITLE
(feat) Add medical supply order type flow to the order basket

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements
- [x] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [x]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR adds a new order type to the Ozone HSC Implementation: **Medical supply order**.

Medical supply orders uses the `Materials` Concept class, along with supporting 2 additional properties to the `Order`, i.e. `Quantity` and `Quantity units`.

The Medical supply order panel is attached to the order basket as an extension and follows the usual flow as of the other present order types.

## Screenshots

https://github.com/user-attachments/assets/455463bf-677f-4ac8-9e38-d5744e379478

## Related Issue
None

### Steps to run
```
yarn start --backend https://oz-hsc-dev.mekomsolutions.net --config-url /openmrs/spa/configs/ozone-frontend-config.json
```

### CODE REVIEW

**Comment by vasharma05** [comment]
The build is failing because the patient common lib it's referencing is updated and not yet merged, hence this PR is dependent on the PR mentioned in the description.
Thanks!

**Comment by usamaidrsk** [comment]
Hi @vasharma05 
Could please add some screenshots or video recording. Plus adding more description on your README.
Also an update on the PR description, how I could test the PR

Thanks

**Comment by vasharma05** [comment]
Hi @usamaidrsk!
The PR description along with the screenshots and steps to run the project is shared as requested.
Thanks!

**Review by usamaidrsk — APPROVED** [review]
LGTM @vasharma05 
You should consider adding the translations too
Thanks

**Comment by vasharma05** [comment]
Hi @rbuisson, please grant @usamaidrsk with the right access.
Thanks!

**Pull request merged**
